name: Open pull request to main repository

on:
  push:
    branches:
      - feature/**

jobs:
  open-pr-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the feature branch
        uses: actions/checkout@v4      

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          pr_title: ${{ github.ref_name }} -> main